--drop table dgmain.leads;

create table dgmain.leads_trans (
lead_id                             int,
lead_guest_guid                     int,
travel_group                        int,
check_in                            date,
check_out                           date,
guaranteed_quote                    text,
source                              text,
num_rooms                           int,
previous_disney_experience          text,
budget                              text,
special_occasion                    text,
adults                              jsonb,
children                            jsonb,
handicap                            text,
handicap_details                    text,
potential_discounts                 jsonb,
unique_pin_info                     text,
other_discount_info                 text,
resort                              text,
resort_accomodations                text,
room_view                           text,
room_bedding                        text,
package_type                        text,
resort_pakage                       text,
num_of_passes                       text,
ticket_type                         text,
ticket_valid_thru                   date,
transportation                      text,
travel_insurance                    text,
memory_maker                        text,
universal_addon                     text,
cruise_addon                        text,
special_requests                    text,
reservation_num                     text,
courtesy_hld_exp_date               date,
final_payment_due_date              date,
refurb                              text,
total_cost                          int,
cost_savings                        text,
discount_applied                    text
);
